language: node_js

node_js:
  - "0.10"

branches:
  except:
    - release

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - sudo gem install compass
  - npm install -g karma grunt-cli bower
  - npm install
  - bower install --dev

script:
  - grunt test:ci
